name: Testing

on:
  push:
    branches: "*"
    tags: "v*"
  pull_request:
    branches: "**"

jobs:
  test:
    name: Test PVGeo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Install PVGeo
        run: pip install -e .[pyproj,omf,discretize]
      - name: Run Test Suite
        run: |
          pytest -v --cov .
          codecov --token=8da9d332-1618-450d-8654-09a8ecf3c2dc
      - name: Build and Publish to PyPI
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload --skip-existing dist/*
